class FacilitiesController < ApplicationController
  def list
    @address1= Facility.where(id:1).distinct.pluck(:address)
    @location1= Facility.where(id:1).distinct.pluck(:location)
    @op_days1= Facility.where(id:1).distinct.pluck(:op_days)
    @op_hours1= Facility.where(id:1).distinct.pluck(:op_hrs)
    @poc_name1= Facility.where(id:1).distinct.pluck(:poc_name)
    @poc_phone1= Facility.where(id:1).distinct.pluck(:poc_phone)
    @poc_cell1= Facility.where(id:1).distinct.pluck(:poc_cell)
    @notes1= Facility.where(id:1).distinct.pluck(:notes)

    @address2= Facility.where(id:2).distinct.pluck(:address)
    @location2= Facility.where(id:2).distinct.pluck(:location)
    @op_days2= Facility.where(id:2).distinct.pluck(:op_days)
    @op_hours2= Facility.where(id:2).distinct.pluck(:op_hrs)
    @poc_name2= Facility.where(id:2).distinct.pluck(:poc_name)
    @poc_phone2= Facility.where(id:2).distinct.pluck(:poc_phone)
    @poc_cell2= Facility.where(id:2).distinct.pluck(:poc_cell)
    @notes2= Facility.where(id:2).distinct.pluck(:notes)

    @address3= Facility.where(id:3).distinct.pluck(:address)
    @location3= Facility.where(id:3).distinct.pluck(:location)
    @op_days3= Facility.where(id:3).distinct.pluck(:op_days)
    @op_hours3= Facility.where(id:3).distinct.pluck(:op_hrs)
    @poc_name3= Facility.where(id:3).distinct.pluck(:poc_name)
    @poc_phone3= Facility.where(id:3).distinct.pluck(:poc_phone)
    @poc_cell3= Facility.where(id:3).distinct.pluck(:poc_cell)
    @notes3= Facility.where(id:3).distinct.pluck(:notes)

    @address4= Facility.where(id:4).distinct.pluck(:address)
    @location4= Facility.where(id:4).distinct.pluck(:location)
    @op_days4= Facility.where(id:4).distinct.pluck(:op_days)
    @op_hours4= Facility.where(id:4).distinct.pluck(:op_hrs)
    @poc_name4= Facility.where(id:4).distinct.pluck(:poc_name)
    @poc_phone4= Facility.where(id:4).distinct.pluck(:poc_phone)
    @poc_cell4= Facility.where(id:4).distinct.pluck(:poc_cell)
    @notes4= Facility.where(id:4).distinct.pluck(:notes)

    @address5= Facility.where(id:5).distinct.pluck(:address)
    @location5= Facility.where(id:5).distinct.pluck(:location)
    @op_days5= Facility.where(id:5).distinct.pluck(:op_days)
    @op_hours5= Facility.where(id:5).distinct.pluck(:op_hrs)
    @poc_name5= Facility.where(id:5).distinct.pluck(:poc_name)
    @poc_phone5= Facility.where(id:5).distinct.pluck(:poc_phone)
    @poc_cell5= Facility.where(id:5).distinct.pluck(:poc_cell)
    @notes5= Facility.where(id:5).distinct.pluck(:notes)

    @address6= Facility.where(id:6).distinct.pluck(:address)
    @location6= Facility.where(id:6).distinct.pluck(:location)
    @op_days6= Facility.where(id:6).distinct.pluck(:op_days)
    @op_hours6= Facility.where(id:6).distinct.pluck(:op_hrs)
    @poc_name6= Facility.where(id:6).distinct.pluck(:poc_name)
    @poc_phone6= Facility.where(id:6).distinct.pluck(:poc_phone)
    @poc_cell6= Facility.where(id:6).distinct.pluck(:poc_cell)
    @notes6= Facility.where(id:6).distinct.pluck(:notes)

    @address7= Facility.where(id:7).distinct.pluck(:address)
    @location7= Facility.where(id:7).distinct.pluck(:location)
    @op_days7= Facility.where(id:7).distinct.pluck(:op_days)
    @op_hours7= Facility.where(id:7).distinct.pluck(:op_hrs)
    @poc_name7= Facility.where(id:7).distinct.pluck(:poc_name)
    @poc_phone7= Facility.where(id:7).distinct.pluck(:poc_phone)
    @poc_cell7= Facility.where(id:7).distinct.pluck(:poc_cell)
    @notes7= Facility.where(id:7).distinct.pluck(:notes)

    @address8= Facility.where(id:8).distinct.pluck(:address)
    @location8= Facility.where(id:8).distinct.pluck(:location)
    @op_days8= Facility.where(id:8).distinct.pluck(:op_days)
    @op_hours8= Facility.where(id:8).distinct.pluck(:op_hrs)
    @poc_name8= Facility.where(id:8).distinct.pluck(:poc_name)
    @poc_phone8= Facility.where(id:8).distinct.pluck(:poc_phone)
    @poc_cell8= Facility.where(id:8).distinct.pluck(:poc_cell)
    @notes8= Facility.where(id:8).distinct.pluck(:notes)

    @address9= Facility.where(id:9).distinct.pluck(:address)
    @location9= Facility.where(id:9).distinct.pluck(:location)
    @op_days9= Facility.where(id:9).distinct.pluck(:op_days)
    @op_hours9= Facility.where(id:9).distinct.pluck(:op_hrs)
    @poc_name9= Facility.where(id:9).distinct.pluck(:poc_name)
    @poc_phone9= Facility.where(id:9).distinct.pluck(:poc_phone)
    @poc_cell9= Facility.where(id:9).distinct.pluck(:poc_cell)
    @notes9= Facility.where(id:9).distinct.pluck(:notes)

    @address10= Facility.where(id:10).distinct.pluck(:address)
    @location10= Facility.where(id:10).distinct.pluck(:location)
    @op_days10= Facility.where(id:10).distinct.pluck(:op_days)
    @op_hours10= Facility.where(id:10).distinct.pluck(:op_hrs)
    @poc_name10= Facility.where(id:10).distinct.pluck(:poc_name)
    @poc_phone10= Facility.where(id:10).distinct.pluck(:poc_phone)
    @poc_cell10= Facility.where(id:10).distinct.pluck(:poc_cell)
    @notes10= Facility.where(id:10).distinct.pluck(:notes)

    @address11= Facility.where(id:11).distinct.pluck(:address)
    @location11= Facility.where(id:11).distinct.pluck(:location)
    @op_days11= Facility.where(id:11).distinct.pluck(:op_days)
    @op_hours11= Facility.where(id:11).distinct.pluck(:op_hrs)
    @poc_name11= Facility.where(id:11).distinct.pluck(:poc_name)
    @poc_phone11= Facility.where(id:11).distinct.pluck(:poc_phone)
    @poc_cell11= Facility.where(id:11).distinct.pluck(:poc_cell)
    @notes11= Facility.where(id:11).distinct.pluck(:notes)

    @address12= Facility.where(id:12).distinct.pluck(:address)
    @location12= Facility.where(id:12).distinct.pluck(:location)
    @op_days12= Facility.where(id:12).distinct.pluck(:op_days)
    @op_hours12= Facility.where(id:12).distinct.pluck(:op_hrs)
    @poc_name12= Facility.where(id:12).distinct.pluck(:poc_name)
    @poc_phone12= Facility.where(id:12).distinct.pluck(:poc_phone)
    @poc_cell12= Facility.where(id:12).distinct.pluck(:poc_cell)
    @notes12= Facility.where(id:12).distinct.pluck(:notes)

    @address13= Facility.where(id:13).distinct.pluck(:address)
    @location13= Facility.where(id:13).distinct.pluck(:location)
    @op_days13= Facility.where(id:13).distinct.pluck(:op_days)
    @op_hours13= Facility.where(id:13).distinct.pluck(:op_hrs)
    @poc_name13= Facility.where(id:13).distinct.pluck(:poc_name)
    @poc_phone13= Facility.where(id:13).distinct.pluck(:poc_phone)
    @poc_cell13= Facility.where(id:13).distinct.pluck(:poc_cell)
    @notes13= Facility.where(id:13).distinct.pluck(:notes)

    @address14= Facility.where(id:14).distinct.pluck(:address)
    @location14= Facility.where(id:14).distinct.pluck(:location)
    @op_days14= Facility.where(id:14).distinct.pluck(:op_days)
    @op_hours14= Facility.where(id:14).distinct.pluck(:op_hrs)
    @poc_name14= Facility.where(id:14).distinct.pluck(:poc_name)
    @poc_phone14= Facility.where(id:14).distinct.pluck(:poc_phone)
    @poc_cell14= Facility.where(id:14).distinct.pluck(:poc_cell)
    @notes14= Facility.where(id:14).distinct.pluck(:notes)

    @address15= Facility.where(id:15).distinct.pluck(:address)
    @location15= Facility.where(id:15).distinct.pluck(:location)
    @op_days15= Facility.where(id:15).distinct.pluck(:op_days)
    @op_hours15= Facility.where(id:15).distinct.pluck(:op_hrs)
    @poc_name15= Facility.where(id:15).distinct.pluck(:poc_name)
    @poc_phone15= Facility.where(id:15).distinct.pluck(:poc_phone)
    @poc_cell15= Facility.where(id:15).distinct.pluck(:poc_cell)
    @notes15= Facility.where(id:15).distinct.pluck(:notes)

    @address16= Facility.where(id:16).distinct.pluck(:address)
    @location16= Facility.where(id:16).distinct.pluck(:location)
    @op_days16= Facility.where(id:16).distinct.pluck(:op_days)
    @op_hours16= Facility.where(id:16).distinct.pluck(:op_hrs)
    @poc_name16= Facility.where(id:16).distinct.pluck(:poc_name)
    @poc_phone16= Facility.where(id:16).distinct.pluck(:poc_phone)
    @poc_cell16= Facility.where(id:16).distinct.pluck(:poc_cell)
    @notes16= Facility.where(id:16).distinct.pluck(:notes)

    @address17= Facility.where(id:17).distinct.pluck(:address)
    @location17= Facility.where(id:17).distinct.pluck(:location)
    @op_days17= Facility.where(id:17).distinct.pluck(:op_days)
    @op_hours17= Facility.where(id:17).distinct.pluck(:op_hrs)
    @poc_name17= Facility.where(id:17).distinct.pluck(:poc_name)
    @poc_phone17= Facility.where(id:17).distinct.pluck(:poc_phone)
    @poc_cell17= Facility.where(id:17).distinct.pluck(:poc_cell)
    @notes17= Facility.where(id:17).distinct.pluck(:notes)

    @address18= Facility.where(id:18).distinct.pluck(:address)
    @location18= Facility.where(id:18).distinct.pluck(:location)
    @op_days18= Facility.where(id:18).distinct.pluck(:op_days)
    @op_hours18= Facility.where(id:18).distinct.pluck(:op_hrs)
    @poc_name18= Facility.where(id:18).distinct.pluck(:poc_name)
    @poc_phone18= Facility.where(id:18).distinct.pluck(:poc_phone)
    @poc_cell18= Facility.where(id:18).distinct.pluck(:poc_cell)
    @notes18= Facility.where(id:18).distinct.pluck(:notes)

    @address19= Facility.where(id:19).distinct.pluck(:address)
    @location19= Facility.where(id:19).distinct.pluck(:location)
    @op_days19= Facility.where(id:19).distinct.pluck(:op_days)
    @op_hours19= Facility.where(id:19).distinct.pluck(:op_hrs)
    @poc_name19= Facility.where(id:19).distinct.pluck(:poc_name)
    @poc_phone19= Facility.where(id:19).distinct.pluck(:poc_phone)
    @poc_cell19= Facility.where(id:19).distinct.pluck(:poc_cell)
    @notes19= Facility.where(id:19).distinct.pluck(:notes)

    @address20= Facility.where(id:20).distinct.pluck(:address)
    @location20= Facility.where(id:20).distinct.pluck(:location)
    @op_days20= Facility.where(id:20).distinct.pluck(:op_days)
    @op_hours20= Facility.where(id:20).distinct.pluck(:op_hrs)
    @poc_name20= Facility.where(id:20).distinct.pluck(:poc_name)
    @poc_phone20= Facility.where(id:20).distinct.pluck(:poc_phone)
    @poc_cell20= Facility.where(id:20).distinct.pluck(:poc_cell)
    @notes20= Facility.where(id:20).distinct.pluck(:notes)

    @address21= Facility.where(id:21).distinct.pluck(:address)
    @location21= Facility.where(id:21).distinct.pluck(:location)
    @op_days21= Facility.where(id:21).distinct.pluck(:op_days)
    @op_hours21= Facility.where(id:21).distinct.pluck(:op_hrs)
    @poc_name21= Facility.where(id:21).distinct.pluck(:poc_name)
    @poc_phone21= Facility.where(id:21).distinct.pluck(:poc_phone)
    @poc_cell21= Facility.where(id:21).distinct.pluck(:poc_cell)
    @notes21= Facility.where(id:21).distinct.pluck(:notes)

    @address22= Facility.where(id:22).distinct.pluck(:address)
    @location22= Facility.where(id:22).distinct.pluck(:location)
    @op_days22= Facility.where(id:22).distinct.pluck(:op_days)
    @op_hours22= Facility.where(id:22).distinct.pluck(:op_hrs)
    @poc_name22= Facility.where(id:22).distinct.pluck(:poc_name)
    @poc_phone22= Facility.where(id:22).distinct.pluck(:poc_phone)
    @poc_cell22= Facility.where(id:22).distinct.pluck(:poc_cell)
    @notes22= Facility.where(id:22).distinct.pluck(:notes)

    @address23= Facility.where(id:23).distinct.pluck(:address)
    @location23= Facility.where(id:23).distinct.pluck(:location)
    @op_days23= Facility.where(id:23).distinct.pluck(:op_days)
    @op_hours23= Facility.where(id:23).distinct.pluck(:op_hrs)
    @poc_name23= Facility.where(id:23).distinct.pluck(:poc_name)
    @poc_phone23= Facility.where(id:23).distinct.pluck(:poc_phone)
    @poc_cell23= Facility.where(id:23).distinct.pluck(:poc_cell)
    @notes23= Facility.where(id:23).distinct.pluck(:notes)

    @address24= Facility.where(id:24).distinct.pluck(:address)
    @location24= Facility.where(id:24).distinct.pluck(:location)
    @op_days24= Facility.where(id:24).distinct.pluck(:op_days)
    @op_hours24= Facility.where(id:24).distinct.pluck(:op_hrs)
    @poc_name24= Facility.where(id:24).distinct.pluck(:poc_name)
    @poc_phone24= Facility.where(id:24).distinct.pluck(:poc_phone)
    @poc_cell24= Facility.where(id:24).distinct.pluck(:poc_cell)
    @notes24= Facility.where(id:24).distinct.pluck(:notes)

    @address25= Facility.where(id:25).distinct.pluck(:address)
    @location25= Facility.where(id:25).distinct.pluck(:location)
    @op_days25= Facility.where(id:25).distinct.pluck(:op_days)
    @op_hours25= Facility.where(id:25).distinct.pluck(:op_hrs)
    @poc_name25= Facility.where(id:25).distinct.pluck(:poc_name)
    @poc_phone25= Facility.where(id:25).distinct.pluck(:poc_phone)
    @poc_cell25= Facility.where(id:25).distinct.pluck(:poc_cell)
    @notes25= Facility.where(id:25).distinct.pluck(:notes)

    @address26= Facility.where(id:26).distinct.pluck(:address)
    @location26= Facility.where(id:26).distinct.pluck(:location)
    @op_days26= Facility.where(id:26).distinct.pluck(:op_days)
    @op_hours26= Facility.where(id:26).distinct.pluck(:op_hrs)
    @poc_name26= Facility.where(id:26).distinct.pluck(:poc_name)
    @poc_phone26= Facility.where(id:26).distinct.pluck(:poc_phone)
    @poc_cell26= Facility.where(id:26).distinct.pluck(:poc_cell)
    @notes26= Facility.where(id:26).distinct.pluck(:notes)

    @address27= Facility.where(id:27).distinct.pluck(:address)
    @location27= Facility.where(id:27).distinct.pluck(:location)
    @op_days27= Facility.where(id:27).distinct.pluck(:op_days)
    @op_hours27= Facility.where(id:27).distinct.pluck(:op_hrs)
    @poc_name27= Facility.where(id:27).distinct.pluck(:poc_name)
    @poc_phone27= Facility.where(id:27).distinct.pluck(:poc_phone)
    @poc_cell27= Facility.where(id:27).distinct.pluck(:poc_cell)
    @notes27= Facility.where(id:27).distinct.pluck(:notes)

    @address28= Facility.where(id:28).distinct.pluck(:address)
    @location28= Facility.where(id:28).distinct.pluck(:location)
    @op_days28= Facility.where(id:28).distinct.pluck(:op_days)
    @op_hours28= Facility.where(id:28).distinct.pluck(:op_hrs)
    @poc_name28= Facility.where(id:28).distinct.pluck(:poc_name)
    @poc_phone28= Facility.where(id:28).distinct.pluck(:poc_phone)
    @poc_cell28= Facility.where(id:28).distinct.pluck(:poc_cell)
    @notes28= Facility.where(id:28).distinct.pluck(:notes)

    @address29= Facility.where(id:29).distinct.pluck(:address)
    @location29= Facility.where(id:29).distinct.pluck(:location)
    @op_days29= Facility.where(id:29).distinct.pluck(:op_days)
    @op_hours29= Facility.where(id:29).distinct.pluck(:op_hrs)
    @poc_name29= Facility.where(id:29).distinct.pluck(:poc_name)
    @poc_phone29= Facility.where(id:29).distinct.pluck(:poc_phone)
    @poc_cell29= Facility.where(id:29).distinct.pluck(:poc_cell)
    @notes29= Facility.where(id:29).distinct.pluck(:notes)

    @address30= Facility.where(id:30).distinct.pluck(:address)
    @location30= Facility.where(id:30).distinct.pluck(:location)
    @op_days30= Facility.where(id:30).distinct.pluck(:op_days)
    @op_hours30= Facility.where(id:30).distinct.pluck(:op_hrs)
    @poc_name30= Facility.where(id:30).distinct.pluck(:poc_name)
    @poc_phone30= Facility.where(id:30).distinct.pluck(:poc_phone)
    @poc_cell30= Facility.where(id:30).distinct.pluck(:poc_cell)
    @notes30= Facility.where(id:30).distinct.pluck(:notes)

    @address31= Facility.where(id:31).distinct.pluck(:address)
    @location31= Facility.where(id:31).distinct.pluck(:location)
    @op_days31= Facility.where(id:31).distinct.pluck(:op_days)
    @op_hours31= Facility.where(id:31).distinct.pluck(:op_hrs)
    @poc_name31= Facility.where(id:31).distinct.pluck(:poc_name)
    @poc_phone31= Facility.where(id:31).distinct.pluck(:poc_phone)
    @poc_cell31= Facility.where(id:31).distinct.pluck(:poc_cell)
    @notes31= Facility.where(id:31).distinct.pluck(:notes)

    @address32= Facility.where(id:32).distinct.pluck(:address)
    @location32= Facility.where(id:32).distinct.pluck(:location)
    @op_days32= Facility.where(id:32).distinct.pluck(:op_days)
    @op_hours32= Facility.where(id:32).distinct.pluck(:op_hrs)
    @poc_name32= Facility.where(id:32).distinct.pluck(:poc_name)
    @poc_phone32= Facility.where(id:32).distinct.pluck(:poc_phone)
    @poc_cell32= Facility.where(id:32).distinct.pluck(:poc_cell)
    @notes32= Facility.where(id:32).distinct.pluck(:notes)

    @address33= Facility.where(id:33).distinct.pluck(:address)
    @location33= Facility.where(id:33).distinct.pluck(:location)
    @op_days33= Facility.where(id:33).distinct.pluck(:op_days)
    @op_hours33= Facility.where(id:33).distinct.pluck(:op_hrs)
    @poc_name33= Facility.where(id:33).distinct.pluck(:poc_name)
    @poc_phone33= Facility.where(id:33).distinct.pluck(:poc_phone)
    @poc_cell33= Facility.where(id:33).distinct.pluck(:poc_cell)
    @notes33= Facility.where(id:33).distinct.pluck(:notes)

    @address34= Facility.where(id:34).distinct.pluck(:address)
    @location34= Facility.where(id:34).distinct.pluck(:location)
    @op_days34= Facility.where(id:34).distinct.pluck(:op_days)
    @op_hours34= Facility.where(id:34).distinct.pluck(:op_hrs)
    @poc_name34= Facility.where(id:34).distinct.pluck(:poc_name)
    @poc_phone34= Facility.where(id:34).distinct.pluck(:poc_phone)
    @poc_cell34= Facility.where(id:34).distinct.pluck(:poc_cell)
    @notes34= Facility.where(id:34).distinct.pluck(:notes)

    @address35= Facility.where(id:35).distinct.pluck(:address)
    @location35= Facility.where(id:35).distinct.pluck(:location)
    @op_days35= Facility.where(id:35).distinct.pluck(:op_days)
    @op_hours35= Facility.where(id:35).distinct.pluck(:op_hrs)
    @poc_name35= Facility.where(id:35).distinct.pluck(:poc_name)
    @poc_phone35= Facility.where(id:35).distinct.pluck(:poc_phone)
    @poc_cell35= Facility.where(id:35).distinct.pluck(:poc_cell)
    @notes35= Facility.where(id:35).distinct.pluck(:notes)

    @address36= Facility.where(id:36).distinct.pluck(:address)
    @location36= Facility.where(id:36).distinct.pluck(:location)
    @op_days36= Facility.where(id:36).distinct.pluck(:op_days)
    @op_hours36= Facility.where(id:36).distinct.pluck(:op_hrs)
    @poc_name36= Facility.where(id:36).distinct.pluck(:poc_name)
    @poc_phone36= Facility.where(id:36).distinct.pluck(:poc_phone)
    @poc_cell36= Facility.where(id:36).distinct.pluck(:poc_cell)
    @notes36= Facility.where(id:36).distinct.pluck(:notes)

    @address37= Facility.where(id:37).distinct.pluck(:address)
    @location37= Facility.where(id:37).distinct.pluck(:location)
    @op_days37= Facility.where(id:37).distinct.pluck(:op_days)
    @op_hours37= Facility.where(id:37).distinct.pluck(:op_hrs)
    @poc_name37= Facility.where(id:37).distinct.pluck(:poc_name)
    @poc_phone37= Facility.where(id:37).distinct.pluck(:poc_phone)
    @poc_cell37= Facility.where(id:37).distinct.pluck(:poc_cell)
    @notes37= Facility.where(id:37).distinct.pluck(:notes)

    @address38= Facility.where(id:38).distinct.pluck(:address)
    @location38= Facility.where(id:38).distinct.pluck(:location)
    @op_days38= Facility.where(id:38).distinct.pluck(:op_days)
    @op_hours38= Facility.where(id:38).distinct.pluck(:op_hrs)
    @poc_name38= Facility.where(id:38).distinct.pluck(:poc_name)
    @poc_phone38= Facility.where(id:38).distinct.pluck(:poc_phone)
    @poc_cell38= Facility.where(id:38).distinct.pluck(:poc_cell)
    @notes38= Facility.where(id:38).distinct.pluck(:notes)

    @address39= Facility.where(id:39).distinct.pluck(:address)
    @location39= Facility.where(id:39).distinct.pluck(:location)
    @op_days39= Facility.where(id:39).distinct.pluck(:op_days)
    @op_hours39= Facility.where(id:39).distinct.pluck(:op_hrs)
    @poc_name39= Facility.where(id:39).distinct.pluck(:poc_name)
    @poc_phone39= Facility.where(id:39).distinct.pluck(:poc_phone)
    @poc_cell39= Facility.where(id:39).distinct.pluck(:poc_cell)
    @notes39= Facility.where(id:39).distinct.pluck(:notes)

    @address40= Facility.where(id:40).distinct.pluck(:address)
    @location40= Facility.where(id:40).distinct.pluck(:location)
    @op_days40= Facility.where(id:40).distinct.pluck(:op_days)
    @op_hours40= Facility.where(id:40).distinct.pluck(:op_hrs)
    @poc_name40= Facility.where(id:40).distinct.pluck(:poc_name)
    @poc_phone40= Facility.where(id:40).distinct.pluck(:poc_phone)
    @poc_cell40= Facility.where(id:40).distinct.pluck(:poc_cell)
    @notes40= Facility.where(id:40).distinct.pluck(:notes)

    @address41= Facility.where(id:41).distinct.pluck(:address)
    @location41= Facility.where(id:41).distinct.pluck(:location)
    @op_days41= Facility.where(id:41).distinct.pluck(:op_days)
    @op_hours41= Facility.where(id:41).distinct.pluck(:op_hrs)
    @poc_name41= Facility.where(id:41).distinct.pluck(:poc_name)
    @poc_phone41= Facility.where(id:41).distinct.pluck(:poc_phone)
    @poc_cell41= Facility.where(id:41).distinct.pluck(:poc_cell)
    @notes41= Facility.where(id:41).distinct.pluck(:notes)

    @address42= Facility.where(id:42).distinct.pluck(:address)
    @location42= Facility.where(id:42).distinct.pluck(:location)
    @op_days42= Facility.where(id:42).distinct.pluck(:op_days)
    @op_hours42= Facility.where(id:42).distinct.pluck(:op_hrs)
    @poc_name42= Facility.where(id:42).distinct.pluck(:poc_name)
    @poc_phone42= Facility.where(id:42).distinct.pluck(:poc_phone)
    @poc_cell42= Facility.where(id:42).distinct.pluck(:poc_cell)
    @notes42= Facility.where(id:42).distinct.pluck(:notes)


  end
end
